
public class adminUtils {
    public static String header(String title) {
        StringBuilder str = new StringBuilder();

        str.append("<!DOCTYPE html>");
        str.append("<html lang='en'>");
        str.append("<head>");

        str.append("<!-- Basic Page Needs -->");
        str.append("<title>Help Hunters");
        str.append("</title>");
        str.append("<meta charset='utf-8'>");
        str.append("<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>");

        str.append("<!-- CSS -->");
        str.append("<link rel='stylesheet' href='css/style.css'>");
        str.append("<link rel='stylesheet' href='css/colors/blue.css'>");
        str.append("</head>");
        str.append("<body class='gray'>");
        str.append("<!-- Wrapper -->");
        str.append("<div id='wrapper'>");
        str.append("<!-- Header Container-->");

        str.append("<header id='header-container' class='fullwidth dashboard-header not-sticky'>");
          str.append("<!-- Header -->");
          str.append("<div id='header'>");
            str.append("<div class='container'>");
              str.append("<!-- Left Side Content -->");
              str.append("<div class='left-side'>");
                str.append("<!-- Logo -->");
                str.append("<div id='logo'>");
                  str.append("<a href='INICIO.html'>");
                    str.append("<img src='images/logo.png' alt=''>");
                  str.append("</a>");
                str.append("</div>");

                str.append("<!-- User Menu -->");
                str.append("<div class='header-widget'>");
                  str.append("<!-- Messages -->");
                  str.append("<div class='header-notifications user-menu'>");
                    str.append("<div class='header-notifications-trigger'>");
                      str.append("<a href='#'>");
                        str.append("<div class='user-avatar status-online'>");
                          str.append("<img src='images/user-avatar-small-01.jpg' alt=''>");
                        str.append("</div>");
                      str.append("</a>");
                    str.append("</div>");

                    str.append("<!-- Dropdown -->");
                    str.append("<div class='header-notifications-dropdown'>");
                      str.append("<!-- User Status -->");
                      str.append("<div class='user-status'>");
                        str.append("<!-- User Name / Avatar -->");
                        str.append("<div class='user-details'>");
                          str.append("<div class='user-avatar status-online'>");
                            str.append("<img src='images/user-avatar-small-01.jpg' alt=''>");
                          str.append("</div>");
                          str.append("<div class='user-name'>Tom Smith ");
                            str.append("<span>Administrator");
                            str.append("</span>");
                          str.append("</div>");
                        str.append("</div>");

                        str.append("<!-- User Status Switcher -->");
                        str.append("<div class='status-switch' id='snackbar-user-status'>");
                          str.append("<label class='user-online current-status'>Online");
                          str.append("</label>");
                          str.append("<label class='user-invisible'>Invisible");
                          str.append("</label>");
                          str.append("<!-- Status Indicator -->");
                          str.append("<span class='status-indicator' aria-hidden='true'>");
                          str.append("</span>");
                        str.append("</div>");
                    str.append("</div>");
                    str.append("<ul class='user-menu-small-nav'>");
                      str.append("<li>");
                      str.append("<a href='settings.html'>");
                        str.append("<i class='icon-material-outline-settings'>");
                        str.append("</i> Settings");
                      str.append("</a>");
                    str.append("</li>");
                      str.append("<li>");
                        str.append("<a href='INICIO.html'>");
                        str.append("<i class='icon-material-outline-power-settings-new'>");
                        str.append("</i> Logout");
                      str.append("</a>");
                    str.append("</li>");
                  str.append("</ul>");
                str.append("</div>");
              str.append("</div>");
            str.append("</div>");
                str.append("<!-- User Menu / End -->");
                str.append("<!-- Mobile Navigation Button -->");
                str.append("<span class='mmenu-trigger'>");
                  str.append("<button class='hamburger hamburger--collapse' type='button'>");
                    str.append("<span class='hamburger-box'>");
                      str.append("<span class='hamburger-inner'>");
                      str.append("</span>");
                    str.append("</span>");
                  str.append("</button>");
                str.append("</span>");
              str.append("</div>");
              str.append("<!-- Right Side Content / End -->");
            str.append("</div>");
          str.append("</div>");
          str.append("<!-- Header / End -->");
        str.append("</header>");
        str.append("<div class='clearfix'>");
        str.append("</div>");
        str.append("<!-- Header Container / End -->");
        str.append("<!-- Dashboard Container -->");
        str.append("<div class='dashboard-container'>");
          str.append("<!-- Dashboard Sidebar -->");
          str.append("<div class='dashboard-sidebar'>");
            str.append("<div class='dashboard-sidebar-inner' data-simplebar>");
              str.append("<div class='dashboard-nav-container'>");
                str.append("<!-- Navigation -->");
                str.append("<div class='dashboard-nav'>");
                  str.append("<div class='dashboard-nav-inner'>");

                  //The purple start header starts here
                    str.append("<ul data-submenu-title='Start'>");
                      str.append("<li>");
                        str.append("<a href=''>");
                        str.append("<i class='icon-material-outline-dashboard'>");
                        str.append("</i> Requests");
                      str.append("</a>");
                    str.append("</li>");
                      str.append("<li>");
                        str.append("<a href=''>");
                        str.append("<i class='icon-material-outline-question-answer'>");
                        str.append("</i> Clients ");
                      str.append("</a>");
                    str.append("</li>");
                      str.append("<li>");
                        str.append("<a href=''>");
                        str.append("<i class='icon-material-outline-star-border'>");
                        str.append("</i> Caretakers");
                      str.append("</a>");
                    str.append("</li>");
                      str.append("<li>");
                        str.append("<a href=''>");
                          str.append("<i class='icon-material-outline-rate-review'>");
                          str.append("</i> Incidences");
                        str.append("</a>");
                      str.append("</li>");
                    str.append("</ul>");

                    //The purple analytics header starts here
                    str.append("<ul data-submenu-title='Analytics'>");
                      str.append("<li>");
                        str.append("<a href=''>");
                        str.append("<i class='icon-material-outline-dashboard'>");
                        str.append("</i> Incidents");
                      str.append("</a>");
                    str.append("</li>");
                      str.append("<li>");
                        str.append("<a href=''>");
                        str.append("<i class='icon-material-outline-question-answer'>");
                        str.append("</i> Caregivers ");
                      str.append("</a>");
                    str.append("</li>");
                      str.append("<li>");
                        str.append("<a href=''>");
                        str.append("<i class='icon-material-outline-star-border'>");
                        str.append("</i> Clients");
                      str.append("</a>");
                    str.append("</li>");
                      str.append("<li>");
                        str.append("<a href=''>");
                          str.append("<i class='icon-material-outline-rate-review'>");
                          str.append("</i> Job offers");
                        str.append("</a>");
                      str.append("</li>");
                    str.append("</ul>");

                    //The purple account header starts here
                    str.append("<ul data-submenu-title='Account'>");
                      str.append("<li>");
                        str.append("<a href='settings.html'>");
                        str.append("<i class='icon-material-outline-settings'>");
                        str.append("</i> Settings");
                      str.append("</a>");
                    str.append("</li>");
                      str.append("<li>");
                        str.append("<a href=''>");
                          str.append("<i class='icon-material-outline-power-settings-new'>");
                          str.append("</i>Logout");
                        str.append("</a>");
                      str.append("</li>");
                    str.append("</ul>");
                  str.append("</div>");
                str.append("</div>");
                str.append("<!-- Navigation / End -->");
              str.append("</div>");
            str.append("</div>");
          str.append("</div>");
          str.append("<!-- Dashboard Sidebar / End -->");

        return str.toString();
    }

    public static String footer(String title) {
        StringBuilder str = new StringBuilder();

        //We will now print out our footer
                str.append("<!-- Footer -->");
          			str.append("<div class='dashboard-footer-spacer'>");
                str.append("</div>");
          			str.append("<div class='small-footer margin-top-15'>");
          				str.append("<div class='small-footer-copyrights'>  © 2020 ");
                    str.append("<strong>Help Hunters");
                    str.append("</strong>. All Rights Reserved.");
          				str.append("</div>");
          				str.append("<ul class='footer-social-links'>");
          					str.append("<li>");
          						str.append("<a href='#' title='Facebook' data-tippy-placement='top'>");
          							str.append("<i class='icon-brand-facebook-f'>");
                        str.append("</i>");
          						str.append("</a>");
          					str.append("</li>");
          					str.append("<li>");
          						str.append("<a href='#' title='Twitter' data-tippy-placement='top'>");
          							str.append("<i class='icon-brand-twitter'>");
                        str.append("</i>");
          						str.append("</a>");
          					str.append("</li>");
          					str.append("<li>");
          						str.append("<a href='#' title='Google Plus' data-tippy-placement='top'>");
          							str.append("<i class='icon-brand-google-plus-g'>");
                        str.append("</i>");
          						str.append("</a>");
          					str.append("</li>");
          					str.append("<li>");
          						str.append("<a href='#' title='LinkedIn' data-tippy-placement='top'>");
          							str.append("<i class='icon-brand-linkedin-in'>");
                        str.append("</i>");
          						str.append("</a>");
          					str.append("</li>");
          				str.append("</ul>");
          				str.append("<div class='clearfix'>");
                  str.append("</div>");
          			str.append("</div>");
          			str.append("<!-- Footer / End -->");
          		str.append("</div>");
          	str.append("</div>");
          	str.append("<!-- Dashboard Content / End -->");
          str.append("</div>");
          str.append("<!-- Dashboard Container / End -->");
          str.append("</div>");
          str.append("<!-- Wrapper / End -->");

      //Now we will print out all of out js dependencies and where we will add if we need more
          str.append("<!-- Scripts -->");
          str.append("<script src='js/jquery-3.4.1.min.js'>");
          str.append("</script>");
          str.append("<script src='js/jquery-migrate-3.1.0.min.js'>");
          str.append("</script>");
          str.append("<script src='js/mmenu.min.js'>");
          str.append("</script>");
          str.append("<script src='js/tippy.all.min.js'>");
          str.append("</script>");
          str.append("<script src='js/simplebar.min.js'>");
          str.append("</script>");
          str.append("<script src='js/bootstrap-slider.min.js'>");
          str.append("</script>");
          str.append("<script src='js/bootstrap-select.min.js'>");
          str.append("</script>");
          str.append("<script src='js/snackbar.js'>");
          str.append("</script>");
          str.append("<script src='js/clipboard.min.js'>");
          str.append("</script>");
          str.append("<script src='js/counterup.min.js'>");
          str.append("</script>");
          str.append("<script src='js/magnific-popup.min.js'>");
          str.append("</script>");
          str.append("<script src='js/slick.min.js'>");
          str.append("</script>");
          str.append("<script src='js/custom.js'>");
          str.append("</script>");
          str.append("<!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->");
          str.append("<script src='js/snackbarLabel.js'>");
          str.append("</script>");
          str.append("</body>");
          str.append("</html>");

        return str.toString();
    }
}
