public class CaregiverUtils {

    public static String header(String user) {
		 
        StringBuilder str = new StringBuilder();
        str.append("<!DOCTYPE HTML>");
        str.append("<html>");
		str.append("<html lang='en'>");
		str.append("<head>");
		str.append("<title>Help Hunters</title>");
		str.append("<meta charset='utf-8'>");
		str.append("<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>");
		str.append("<link rel='stylesheet' href='css/style.css'>");
		str.append("<link rel='stylesheet' href='css/colors/blue.css'>");
		str.append("</head>");
		str.append("<body>");
		str.append("<div id='wrapper' class='wrapper-with-transparent-header'>");
		str.append("<header id='header-container' class='fullwidth transparent-header'>");
		str.append("<div id='header'>");
		str.append("<div class='container'>");
		str.append("<div class='left-side'>");
		str.append("<div id='logo'>");
		str.append("<a href='INICIO.html'><img src='images/logo.png' data-sticky-logo='images/logo.png' data-transparent-logo='images/logo.png' alt=''></a>");
		str.append("</div>");
		str.append("</div>");
		str.append("<div class='right-side'>");
		str.append("<div class='header-widget'>");
		str.append("<div class='header-notifications user-menu'>");
		str.append("<div class='header-notifications-trigger'>");
		str.append("<a href='#'><div class='user-avatar status-online'><img src='images/random.png' alt=''></div></a>");
		str.append("</div>");
		str.append("<div class='header-notifications-dropdown'>");
		str.append("<div class='user-status'>");
		str.append("<div class='user-details'>");
		str.append("<div class='user-avatar status-online'><img src='images/random.png' alt=''></div>");
		str.append("<div class='user-name'>");
		str.append(""+ user +"");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("<ul class='user-menu-small-nav'>");
		str.append("<li><a href='dashboard'><i class='icon-material-outline-dashboard'></i> Dashboard </a></li>");
		str.append("<li><a href='caregiverProfile'><i class='icon-material-outline-face'></i> View my Profile </a></li>");
		str.append("<li><a href='CaregiverReviews'><i class='icon-material-outline-star'></i> Reviews </a></li>");
		str.append("<li><a href='CaregiverSettings'><i class='icon-material-outline-settings'></i> Settings</a></li>");
		str.append("<li><a href='INICIO.html'><i class='icon-material-outline-power-settings-new'></i> Logout</a></li>");
		str.append("</ul>");
		str.append("");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</header>");
		str.append("<div class='clearfix'></div>");
		return str.toString();
	 }
    public static String footer(String user) {
        StringBuilder str = new StringBuilder();
		str.append("<div id='footer'>");
		str.append("<div class='footer-top-section'>");
		str.append("<div class='container'>");
		str.append("<div class='row'>");
		str.append("<div class='col-xl-12'>");
		str.append("<div class='footer-rows-container'>");
		str.append("<div class='footer-rows-left'>");
		str.append("<div class='footer-row'>");
		str.append("<div class='footer-row-inner footer-logo'>");
		str.append("<img src='images/logo.png' alt=''>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("<div class='footer-rows-right'>");
		str.append("<div class='footer-row'>");
		str.append("<div class='footer-row-inner'>");
		str.append("<ul class='footer-social-links'>");
		str.append("<li>");
		str.append("<a href='facebook.com' title='Facebook' data-tippy-placement='bottom' data-tippy-theme='light'>");
		str.append("<i class='icon-brand-facebook-f'></i>");
		str.append("</a>");
		str.append("</li>");
		str.append("<li>");
		str.append("<a href='twitter.com' title='Twitter' data-tippy-placement='bottom' data-tippy-theme='light'>");
		str.append("<i class='icon-brand-twitter'></i>");
		str.append("</a>");
		str.append("</li>");
		str.append("<li>");
		str.append("<a href='google.com' title='Google Plus' data-tippy-placement='bottom' data-tippy-theme='light'>");
		str.append("<i class='icon-brand-google-plus-g'></i>");
		str.append("</a>");
		str.append("</li>");
		str.append("<li>");
		str.append("<a href='linkedin.com' title='LinkedIn' data-tippy-placement='bottom' data-tippy-theme='light'>");
		str.append("<i class='icon-brand-linkedin-in'></i>");
		str.append("</a>");
		str.append("</li>");
		str.append("</ul>");
		str.append("<div class='clearfix'></div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("<div class='footer-bottom-section'>");
		str.append("<div class='container'>");
		str.append("<div class='row'>");
		str.append("<div class='col-xl-12'>");
		str.append("© 2020 <strong>Help Hunters</strong>. All Rights Reserved.");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("</div>");
		str.append("<script src='js/jquery-3.4.1.min.js'></script>");
		str.append("<script src='js/jquery-migrate-3.1.0.min.js'></script>");
		str.append("<script src='js/mmenu.min.js'></script>");
		str.append("<script src='js/tippy.all.min.js'></script>");
		str.append("<script src='js/simplebar.min.js'></script>");
		str.append("<script src='js/bootstrap-slider.min.js'></script>");
		str.append("<script src='js/bootstrap-select.min.js'></script>");
		str.append("<script src='js/snackbar.js'></script>");
		str.append("<script src='js/clipboard.min.js'></script>");
		str.append("<script src='js/counterup.min.js'></script>");
		str.append("<script src='js/magnific-popup.min.js'></script>");
		str.append("<script src='js/slick.min.js'></script>");
		str.append("<script src='js/custom.js'></script>");
        str.append("</body>");
        str.append("</html>");
        return str.toString();
    }
    
    public static String headerLogInCaregiver(){
        
        /* 
        
        Esta funcion de Utils me va a servir para llamar todo el html que necesito por ahora a mi 
        login de Caregiver, todo lo demas sera estatico menos el form propio de caregiver.
        
        Esta funcion la voy a llamar en CaregiverLogin.java,
        mas adelante tendremos que hacer uno que sea 
        junto para todos.
            
        */
        
        StringBuilder str = new StringBuilder();
        
        str.append("<!doctype html>");
        str.append("<html lang='en'>");
        str.append("<head>");
        str.append("");
        str.append("<!-- Basic Page Needs");
        str.append("================================================== -->");
        str.append("<title>Help Hunters</title>");
        str.append("<meta charset='utf-8'>");
        str.append("<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>");
        str.append("");
        str.append("<!-- CSS");
        str.append("================================================== -->");
        str.append("<link rel='stylesheet' href='css/style.css'>");
        str.append("<link rel='stylesheet' href='css/colors/blue.css'>");
        str.append("");
        str.append("</head>");
        str.append("<body>");
        str.append("");
        str.append("<!-- Wrapper -->");
        str.append("<div id='wrapper'>");
        str.append("");
        str.append("<!-- Header Container");
        str.append("================================================== -->");
        str.append("<header id='header-container' class='fullwidth transparent'>");
        str.append("");
        str.append("	<!-- Header -->");
        str.append("	<div id='header'>");
        str.append("		<div class='container'>");
        str.append("");
        str.append("			<!-- Left Side Content -->");
        str.append("			<div class='left-side'>");
        str.append("");
        str.append("				<!-- Logo -->");
        str.append("				<div id='logo'>");
        str.append("					<a href='index.html'><img src='images/logo.png' alt=''></a>");
        str.append("				</div>");
        str.append("");
        str.append("				<!-- Main Navigation -->");
        str.append("				<nav id='navigation'>");
        str.append("					<ul id='responsive'>");
        str.append("");
        str.append("				<div class='clearfix'></div>");
        str.append("				<!-- Main Navigation / End -->");
        str.append("");
        str.append("			</div>");
        str.append("			<!-- Left Side Content / End -->");
        str.append("");
        str.append("");
        str.append("			<!-- Right Side Content / End -->");
        str.append("			<div class='right-side'>");
        str.append("");
        str.append("				<div class='header-widget'>");
        str.append("					<a href='#sign-in-dialog' class='popup-with-zoom-anim log-in-button'><i class='icon-feather-log-in'></i> <span>Log In / Register</span></a>");
        str.append("				</div>");
        str.append("");
        str.append("");
        str.append("			</div>");
        str.append("			<!-- Right Side Content / End -->");
        str.append("");
        str.append("		</div>");
        str.append("	</div>");
        str.append("	<!-- Header / End -->");
        str.append("");
        str.append("</header>");
        str.append("<div class='clearfix'></div>");
        str.append("<!-- Header Container / End -->");
        str.append("");
        str.append("");
        str.append("");
        str.append("<!-- Intro Banner");
        str.append("================================================== -->");
        str.append("<!-- add class 'disable-gradient' to enable consistent background overlay -->");
        str.append("<div class='intro-banner' data-background-image='images/home-background.jpg'>");
        str.append("	<div class='container'>");
        str.append("");
        str.append("		<!-- Intro Headline -->");
        str.append("		<div class='row'>");
        str.append("			<div class='col-md-12'>");
        str.append("				<div class='banner-headline'>");
        str.append("					<h3>");
        str.append("						<strong> Hire caregivers in your city </strong>");
        str.append("						<br>");
        str.append("						<span> With <strong class='color'>Help Hunters</strong> your loved ones will be taken care of. </span>");
        str.append("					</h3>");
        str.append("				</div>");
        str.append("			</div>");
        str.append("		</div>");
        str.append("");
        str.append("");
        str.append("		<!-- Stats -->");
        str.append("		<div class='row'>");
        str.append("			<div class='col-md-12'>");
        str.append("				<ul class='intro-stats margin-top-45 hide-under-992px'>");
        str.append("				</ul>");
        str.append("			</div>");
        str.append("		</div>");
        str.append("");
        str.append("	</div>");
        str.append("</div>");
        str.append("");
        str.append("");
        str.append("");
        str.append("");
        str.append("<!-- Footer");
        str.append("================================================== -->");
        str.append("<div id='footer'>");
        str.append("");
        str.append("	<!-- Footer Top Section -->");
        str.append("	<div class='footer-top-section'>");
        str.append("		<div class='container'>");
        str.append("			<div class='row'>");
        str.append("				<div class='col-xl-12'>");
        str.append("");
        str.append("					<!-- Footer Rows Container -->");
        str.append("					<div class='footer-rows-container'>");
        str.append("");
        str.append("						<!-- Left Side -->");
        str.append("						<div class='footer-rows-left'>");
        str.append("							<div class='footer-row'>");
        str.append("								<div class='footer-row-inner footer-logo'>");
        str.append("									<img src='images/logo.png' alt=''>");
        str.append("								</div>");
        str.append("							</div>");
        str.append("						</div>");
        str.append("");
        str.append("						<!-- Right Side -->");
        str.append("						<div class='footer-rows-right'>");
        str.append("");
        str.append("							<!-- Social Icons -->");
        str.append("							<div class='footer-row'>");
        str.append("								<div class='footer-row-inner'>");
        str.append("									<ul class='footer-social-links'>");
        str.append("										<li>");
        str.append("											<a href='#' title='Facebook' data-tippy-placement='bottom' data-tippy-theme='light'>");
        str.append("												<i class='icon-brand-facebook-f'></i>");
        str.append("											</a>");
        str.append("										</li>");
        str.append("										<li>");
        str.append("											<a href='#' title='Twitter' data-tippy-placement='bottom' data-tippy-theme='light'>");
        str.append("												<i class='icon-brand-twitter'></i>");
        str.append("											</a>");
        str.append("										</li>");
        str.append("										<li>");
        str.append("											<a href='#' title='Google Plus' data-tippy-placement='bottom' data-tippy-theme='light'>");
        str.append("												<i class='icon-brand-google-plus-g'></i>");
        str.append("											</a>");
        str.append("										</li>");
        str.append("										<li>");
        str.append("											<a href='#' title='LinkedIn' data-tippy-placement='bottom' data-tippy-theme='light'>");
        str.append("												<i class='icon-brand-linkedin-in'></i>");
        str.append("											</a>");
        str.append("										</li>");
        str.append("									</ul>");
        str.append("									<div class='clearfix'></div>");
        str.append("								</div>");
        str.append("							</div>");
        str.append("");
        str.append("							<!-- Language Switcher -->");
        str.append("");
        str.append("						</div>");
        str.append("");
        str.append("					</div>");
        str.append("					<!-- Footer Rows Container / End -->");
        str.append("				</div>");
        str.append("			</div>");
        str.append("		</div>");
        str.append("	</div>");
        str.append("	<!-- Footer Top Section / End -->");
        str.append("");
        str.append("	<!-- Footer Middle Section -->");
        str.append("	<div class='footer-middle-section'>");
        str.append("		<div class='container'>");
        str.append("			<div class='row'>");
        str.append("");
        str.append("				<!-- Links -->");
        str.append("");
        str.append("");
        str.append("				<!-- Links -->");
        str.append("				<div class='col-xl-2 col-lg-2 col-md-3'>");
        str.append("					<div class='footer-links'>");
        str.append("						<h3>Future Employees</h3>");
        str.append("						<ul>");
        str.append("							<li><a href='REGISTER_CARETAKERS.html'><span>Become a Caregiver</span></a></li>");
        str.append("						</ul>");
        str.append("					</div>");
        str.append("				</div>");
        str.append("");
        str.append("				<!-- Links -->");
        str.append("				<div class='col-xl-2 col-lg-2 col-md-3'>");
        str.append("					<div class='footer-links'>");
        str.append("						<h3>Administrative</h3>");
        str.append("						<ul>");
        str.append("							<li><a href='logadmin.html'><span>Login</span></a></li>");
        str.append("						</ul>");
        str.append("					</div>");
        str.append("				</div>");
        str.append("");
        str.append("			</div>");
        str.append("		</div>");
        str.append("	</div>");
        str.append("	<!-- Footer Middle Section / End -->");
        str.append("");
        str.append("	<!-- Footer Copyrights -->");
        str.append("	<div class='footer-bottom-section'>");
        str.append("		<div class='container'>");
        str.append("			<div class='row'>");
        str.append("				<div class='col-xl-12'>");
        str.append("					© 2020 <strong>Help Hunters</strong>. All Rights Reserved.");
        str.append("				</div>");
        str.append("			</div>");
        str.append("		</div>");
        str.append("	</div>");
        str.append("	<!-- Footer Copyrights / End -->");
        str.append("");
        str.append("</div>");
        str.append("<!-- Footer / End -->");
        str.append("");
        str.append("</div>");
        str.append("<!-- Wrapper / End -->");
        str.append("");
        str.append("");
        str.append("<!-- Sign In Popup");
        str.append("================================================== -->");
        str.append("<div id='sign-in-dialog' class='zoom-anim-dialog mfp-hide dialog-with-tabs'>");
        str.append("");
        str.append("	<!--Tabs -->");
        str.append("	<div class='sign-in-form'>");
        str.append("");
        str.append("		<ul class='popup-tabs-nav'>");
        str.append("			<li><a href='#loginclient'>Clients</a></li>");
        str.append("			<li><a href='#logincaregiver'>Caregivers </a></li>");
        str.append("			<li><a href='#register'>Register as a Client</a></li>");
        str.append("		</ul>");
        str.append("");
        str.append("		<div class='popup-tabs-container'>");
        str.append("");
        str.append("			<!-- Login as a Client -->");
        str.append("			<div class='popup-tab-content' id='loginclient'>");
        str.append("");
        str.append("				<!-- Welcome Text -->");
        str.append("				<div class='welcome-text'>");
        str.append("					<h3>We're glad to see you again!</h3>");
        str.append("				</div>");
        str.append("");
        str.append("				<!-- Form -->");
        str.append("				<form method='get' id='login-form' action='dada.html'>");
        str.append("					<div class='input-with-icon-left'>");
        str.append("						<i class='icon-material-baseline-mail-outline'></i>");
        str.append("						<input type='text' class='input-text with-border' name='emailaddress' id='emailaddress' placeholder='Email Address' required/>");
        str.append("					</div>");
        str.append("");
        str.append("					<div class='input-with-icon-left'>");
        str.append("						<i class='icon-material-outline-lock'></i>");
        str.append("						<input type='password' class='input-text with-border' name='password' id='password' placeholder='Password' required/>");
        str.append("					</div>");
        str.append("					<a href='#' class='forgot-password'>Forgot Password?</a>");
        str.append("				</form>");
        str.append("");
        str.append("				<!-- Button -->");
        str.append("				<button class='button full-width button-sliding-icon ripple-effect' type='submit' form='login-form'>Log In <i class='icon-material-outline-arrow-right-alt'></i></button>");
        str.append("			</div>");
        str.append("");
        str.append("			<!-- Login as a Caregiver -->");
        str.append("			<div class='popup-tab-content' id='logincaregiver'>");
        str.append("");
        str.append("				<!-- Welcome Text -->");
        str.append("				<div class='welcome-text'>");
        str.append("					<h3>We're glad to see you again!</h3>");
        str.append("				</div>");
        str.append("");
        
        return str.toString();
    }
    public static String footerLogInCaregiver(){
        StringBuilder str = new StringBuilder();
        str.append("			</div>");
        str.append("");
        str.append("			<!-- Register -->");
        str.append("			<div class='popup-tab-content' id='register'>");
        str.append("");
        str.append("				<!-- Welcome Text -->");
        str.append("				<div class='welcome-text'>");
        str.append("					<h3>Let's create your account!</h3>");
        str.append("				</div>");
        str.append("");
        str.append("				<!-- Form -->");
        str.append("				<form method='post' id='register-account-form'>");
        str.append("					<div class='input-with-icon-left'>");
        str.append("						<i class='icon-material-baseline-mail-outline'></i>");
        str.append("						<input type='text' class='input-text with-border' name='emailaddress-register' id='emailaddress-register' placeholder='Email Address' required/>");
        str.append("					</div>");
        str.append("");
        str.append("					<div class='input-with-icon-left' title='Should be at least 8 characters long' data-tippy-placement='bottom'>");
        str.append("						<i class='icon-material-outline-lock'></i>");
        str.append("						<input type='password' class='input-text with-border' name='password-register' id='password-register' placeholder='Password' required/>");
        str.append("					</div>");
        str.append("");
        str.append("					<div class='input-with-icon-left'>");
        str.append("						<i class='icon-material-outline-lock'></i>");
        str.append("						<input type='password' class='input-text with-border' name='password-repeat-register' id='password-repeat-register' placeholder='Repeat Password' required/>");
        str.append("					</div>");
        str.append("				</form>");
        str.append("");
        str.append("				<!-- Button -->");
        str.append("				<button class='margin-top-10 button full-width button-sliding-icon ripple-effect' type='submit' form='register-account-form'>Register <i class='icon-material-outline-arrow-right-alt'></i></button>");
        str.append("");
        str.append("			</div>");
        str.append("");
        str.append("		</div>");
        str.append("	</div>");
        str.append("</div>");
        str.append("<!-- Sign In Popup / End -->");
        str.append("");
        str.append("");
        str.append("<!-- Scripts");
        str.append("================================================== -->");
        str.append("<script src='js/jquery-3.4.1.min.js'></script>");
        str.append("<script src='js/jquery-migrate-3.1.0.min.js'></script>");
        str.append("<script src='js/mmenu.min.js'></script>");
        str.append("<script src='js/tippy.all.min.js'></script>");
        str.append("<script src='js/simplebar.min.js'></script>");
        str.append("<script src='js/bootstrap-slider.min.js'></script>");
        str.append("<script src='js/bootstrap-select.min.js'></script>");
        str.append("<script src='js/snackbar.js'></script>");
        str.append("<script src='js/clipboard.min.js'></script>");
        str.append("<script src='js/counterup.min.js'></script>");
        str.append("<script src='js/magnific-popup.min.js'></script>");
        str.append("<script src='js/slick.min.js'></script>");
        str.append("<script src='js/custom.js'></script>");
        str.append("");
        str.append("<!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->");
        str.append("<script>");
        str.append("// Snackbar for user status switcher");
        str.append("$('#snackbar-user-status label').click(function() {");
        str.append("	Snackbar.show({");
        str.append("		text: 'Your status has been changed!',");
        str.append("		pos: 'bottom-center',");
        str.append("		showAction: false,");
        str.append("		actionText: 'Dismiss',");
        str.append("		duration: 3000,");
        str.append("		textColor: '#fff',");
        str.append("		backgroundColor: '#383838'");
        str.append("	});");
        str.append("});");
        str.append("</script>");
        str.append("");
        str.append("");
        str.append("");
        str.append("");
        str.append("</body>");
        str.append("</html>");
        
        return str.toString();
    }
 
    public static String headerCaregiverDashboardAntesDePerfil(String user){
        
        StringBuilder str = new StringBuilder();
        
        str.append("<!doctype html>");
        str.append("<html lang='en'>");
        str.append("<head>");
        str.append("");
        str.append("<!-- Basic Page Needs");
        str.append("================================================== -->");
        str.append("<title>Help Hunters</title>");
        str.append("<meta charset='utf-8'>");
        str.append("<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>");
        str.append("");
        str.append("<!-- CSS");
        str.append("================================================== -->");
        str.append("<link rel='stylesheet' href='css/style.css'>");
        str.append("<link rel='stylesheet' href='css/colors/blue.css'>");
        str.append("");
        str.append("</head>");
        str.append("<body class='gray'>");
        str.append("");
        str.append("<!-- Wrapper -->");
        str.append("<div id='wrapper'>");
        str.append("");
        str.append("<!-- Header Container");
        str.append("================================================== -->");
        str.append("<header id='header-container' class='fullwidth dashboard-header not-sticky'>");
        str.append("");
        str.append("	<!-- Header -->");
        str.append("	<div id='header'>");
        str.append("		<div class='container'>");
        str.append("");
        str.append("			<!-- Left Side Content -->");
        str.append("			<div class='left-side'>");
        str.append("");
        str.append("				<!-- Logo -->");
        str.append("				<div id='logo'>");
        str.append("					<a href='index.html'><img src='images/logo.png' alt=''></a>");
        str.append("				</div>");
        str.append("");
        str.append("");
        str.append("			</div>");
        str.append("			<!-- Left Side Content / End -->");
        str.append("");
        str.append("");
        str.append("			<!-- Right Side Content / End -->");
        str.append("			<div class='right-side'>");
        str.append("");
        str.append("				<!--  User Notifications -->");
        str.append("				<div class='header-widget hide-on-mobile'>");
        str.append("");
        str.append("					<!-- Notifications -->");
        str.append("					<div class='header-notifications'>");
        str.append("");
        str.append("						<!-- Trigger -->");
        str.append("						<div class='header-notifications-trigger'>");
        str.append("						</div>");
        str.append("						<div class='header-notifications-dropdown'>");
        str.append("");
        str.append("							<div class='header-notifications-headline'>");
        str.append("								<h4>Notifications</h4>");
        str.append("								<button class='mark-as-read ripple-effect-dark' title='Mark all as read' data-tippy-placement='left'>");
        str.append("									<i class='icon-feather-check-square'></i>");
        str.append("								</button>");
        str.append("							</div>");
        str.append("");
        str.append("							<div class='header-notifications-content'>");
        str.append("								<div class='header-notifications-scroll' data-simplebar>");
        str.append("									<ul>");
        str.append("										<!-- Notification -->");
        str.append("										<li class='notifications-not-read'>");
        str.append("											<a href='dashboard-manage-jobs.html'>");
        str.append("												<span class='notification-icon'><i class='icon-material-outline-group'></i></span>");
        str.append("												<span class='notification-text'>");
        str.append("													<strong>Carlos Azua</strong> offered you a job <span class='color'></span>");
        str.append("												</span>");
        str.append("											</a>");
        str.append("										</li>");
        str.append("");
        str.append("										<!-- Notification -->");
        str.append("										<li>");
        str.append("											<a href='dashboard-manage-jobs.html'>");
        str.append("												<span class='notification-icon'><i class=' icon-material-outline-group'></i></span>");
        str.append("												<span class='notification-text'>");
        str.append("													<strong>Andrea Perez</strong> offered you a job <span class='color'></span>");
        str.append("												</span>");
        str.append("											</a>");
        str.append("										</li>");
        str.append("");
        str.append("");
        str.append("");
        str.append("									</ul>");
        str.append("								</div>");
        str.append("							</div>");
        str.append("");
        str.append("						</div>");
        str.append("");
        str.append("					</div>");
        str.append("");
        str.append("					<!-- Messages -->");
        str.append("					<div class='header-notifications'>");
        str.append("						<div class='header-notifications-trigger'>");
        
        str.append("						</div>");
        str.append("");
        str.append("						<!-- Dropdown -->");
        str.append("						<div class='header-notifications-dropdown'>");
        str.append("");
        str.append("							<div class='header-notifications-headline'>");
        
        
        str.append("								<button class='mark-as-read ripple-effect-dark' title='Mark all as read' data-tippy-placement='left'>");
        str.append("									<i class='icon-feather-check-square'></i>");
        str.append("								</button>");
        str.append("							</div>");
        str.append("");
        str.append("							<div class='header-notifications-content'>");
        str.append("								<div class='header-notifications-scroll' data-simplebar>");
        str.append("									<ul>");
        str.append("										<!-- Notification -->");
        str.append("										<li class='notifications-not-read'>");
        
        str.append("												<div class='notification-text'>");
        str.append("												</div>");
        str.append("											</a>");
        str.append("										</li>");
        str.append("");
        str.append("");
        str.append("									</ul>");
        str.append("								</div>");
        str.append("							</div>");
        str.append("");
        str.append("						</div>");
        str.append("					</div>");
        str.append("");
        str.append("				</div>");
        str.append("				<!--  User Notifications / End -->");
        str.append("");
        str.append("				<!-- User Menu -->");
        str.append("				<div class='header-widget'>");
        str.append("");
        str.append("					<!-- Messages -->");
        str.append("					<div class='header-notifications user-menu'>");
        str.append("						<div class='header-notifications-trigger'>");
        str.append("							<a href='#'><div class='user-avatar status-online'><img src='images/user-avatar-small-01.jpg' alt=''></div></a>");
        str.append("						</div>");
        str.append("");
        str.append("						<!-- Dropdown -->");
        str.append("						<div class='header-notifications-dropdown'>");
        str.append("");
                      
        return str.toString();
    }
    
    public static String headerCaregiverDashboardDespuesDePerfil(String user, String tipo){
        
        StringBuilder str = new StringBuilder();
        
        str.append("");
        str.append("						<ul class='user-menu-small-nav'>");
        str.append("							<li><a href='dashboard.html'><i class='icon-material-outline-dashboard'></i> Dashboard</a></li>");
        str.append("							<li><a href='dashboard-settings-caretaker.html'><i class='icon-material-outline-settings'></i> Settings</a></li>");
        str.append("							<li><a href='index.html'><i class='icon-material-outline-power-settings-new'></i> Logout</a></li>");
        str.append("						</ul>");
        str.append("");
        str.append("						</div>");
        str.append("					</div>");
        str.append("");
        str.append("				</div>");
        str.append("				<!-- User Menu / End -->");
        str.append("");
        str.append("				<!-- Mobile Navigation Button -->");
        str.append("				<span class='mmenu-trigger'>");
        str.append("					<button class='hamburger hamburger--collapse' type='button'>");
        str.append("						<span class='hamburger-box'>");
        str.append("							<span class='hamburger-inner'></span>");
        str.append("						</span>");
        str.append("					</button>");
        str.append("				</span>");
        str.append("");
        str.append("			</div>");
        str.append("			<!-- Right Side Content / End -->");
        str.append("");
        str.append("		</div>");
        str.append("	</div>");
        str.append("	<!-- Header / End -->");
        str.append("");
        str.append("</header>");
        str.append("<div class='clearfix'></div>");
        str.append("<!-- Header Container / End -->");
        str.append("");
        str.append("");
        str.append("<!-- Dashboard Container -->");
        str.append("<div class='dashboard-container'>");
        str.append("");
        str.append("	<!-- Dashboard Sidebar");
        str.append("	================================================== -->");
        str.append("	<div class='dashboard-sidebar'>");
        str.append("		<div class='dashboard-sidebar-inner' data-simplebar>");
        str.append("			<div class='dashboard-nav-container'>");
        str.append("");
        str.append("				<!-- Responsive Navigation Trigger -->");
        str.append("				<a href='#' class='dashboard-responsive-nav-trigger'>");
        str.append("					<span class='hamburger hamburger--collapse' >");
        str.append("						<span class='hamburger-box'>");
        str.append("							<span class='hamburger-inner'></span>");
        str.append("						</span>");
        str.append("					</span>");
        str.append("					<span class='trigger-title'>Dashboard Navigation</span>");
        str.append("				</a>");
        str.append("");
        str.append("				<!-- Navigation -->");
        str.append("				<div class='dashboard-nav'>");
        str.append("					<div class='dashboard-nav-inner'>");
        str.append("");
        str.append("						<ul data-submenu-title='Start'>");
      
        
        if (tipo =="dashboard"){
            str.append("							<li class='active'><a href='Dashboard'><i class='icon-material-outline-dashboard'></i> Dashboard</a></li>");
            str.append("							<li><a href='CaregiverMsg'><i class='icon-material-outline-question-answer'></i> Messages </a></li>");
            str.append("							<li><a href='NotesCaregiver'><i class='icon-material-outline-note-add'></i> Notes </a></li>");
            } else if (tipo=="messages"){
            str.append("							<li><a href='Dashboard'><i class='icon-material-outline-dashboard'></i> Dashboard</a></li>");
            str.append("							<li class='active'><a href='CaregiverMsg'><i class='icon-material-outline-question-answer'></i> Messages </a></li>");
            str.append("							<li><a href='NotesCaregiver'><i class='icon-material-outline-note-add'></i> Notes </a></li>");
            } else if (tipo=="notes"){
            str.append("							<li><a href='Dashboard'><i class='icon-material-outline-dashboard'></i> Dashboard</a></li>");
            str.append("							<li><a href='CaregiverMsg'><i class='icon-material-outline-question-answer'></i> Messages </a></li>");
            str.append("							<li class='active'><a href='NotesCaregiver'><i class='icon-material-outline-note-add'></i> Notes </a></li>");

        }
        
        
        str.append("							<li><a href='dashboard-reviews-caretaker.html'><i class='icon-material-outline-rate-review'></i> Reviews</a></li>");
        str.append("						</ul>");
        str.append("");
        str.append("						<ul data-submenu-title='Organize and Manage'>");
        str.append("							<li><a href='#'><i class='icon-material-outline-business-center'></i> Jobs</a>");
        str.append("								<ul>");
        str.append("									<li><a href='dashboard-manage-jobs.html'>Manage Jobs <span class='nav-tag'>3</span></a></li>");
        str.append("								</ul>");
        str.append("							</li>");
        str.append("");
        str.append("						</ul>");
        str.append("");
        str.append("						<ul data-submenu-title='Account'>");
        str.append("							<li><a href='dashboard-settings-caretaker.html'><i class='icon-material-outline-settings'></i> Settings</a></li>");
        str.append("							<li><a href='index-logged-out.html'><i class='icon-material-outline-power-settings-new'></i> Logout</a></li>");
        str.append("						</ul>");
        str.append("");
        str.append("					</div>");
        str.append("				</div>");
        str.append("				<!-- Navigation / End -->");
        str.append("");
        str.append("			</div>");
        str.append("		</div>");
        str.append("	</div>");
        str.append("	<!-- Dashboard Sidebar / End -->");
        str.append("");
        str.append("");
                      
        return str.toString();
    }
    
    public static String footerCaregiverDashboard(){
        
        StringBuilder str = new StringBuilder();
        
        str.append("");
        str.append("</div>");
        str.append("<!-- Dashboard Container / End -->");
        str.append("");
        str.append("</div>");
        str.append("<!-- Wrapper / End -->");
        str.append("");
        str.append("");
        str.append("<!-- Apply for a job popup");
        str.append("================================================== -->");
        str.append("<div id='small-dialog' class='zoom-anim-dialog mfp-hide dialog-with-tabs'>");
        str.append("");
        str.append("	<!--Tabs -->");
        str.append("	<div class='sign-in-form'>");
        str.append("");
        str.append("		<ul class='popup-tabs-nav'>");
        str.append("			<li><a href='#tab'>Add Note</a></li>");
        str.append("		</ul>");
        str.append("");
        str.append("		<div class='popup-tabs-container'>");
        str.append("");
        str.append("			<!-- Tab -->");
        str.append("			<div class='popup-tab-content' id='tab'>");
        str.append("");
        str.append("				<!-- Welcome Text -->");
        str.append("				<div class='welcome-text'>");
        str.append("					<h3>Do Not Forget 😎</h3>");
        str.append("				</div>");
        str.append("");
        str.append("				<!-- Form -->");
        str.append("				<form method='post' id='add-note'>");
        str.append("");
        str.append("					<select class='selectpicker with-border default margin-bottom-20' data-size='7' title='Priority'>");
        str.append("						<option>Low Priority</option>");
        str.append("						<option>Medium Priority</option>");
        str.append("						<option>High Priority</option>");
        str.append("					</select>");
        str.append("");
        str.append("					<textarea name='textarea' cols='10' placeholder='Note' class='with-border'></textarea>");
        str.append("");
        str.append("				</form>");
        str.append("");
        str.append("				<!-- Button -->");
        str.append("				<button class='button full-width button-sliding-icon ripple-effect' type='submit' form='add-note'>Add Note <i class='icon-material-outline-arrow-right-alt'></i></button>");
        str.append("");
        str.append("			</div>");
        str.append("");
        str.append("		</div>");
        str.append("	</div>");
        str.append("</div>");
        str.append("<!-- Apply for a job popup / End -->");
        str.append("");
        str.append("");
        str.append("<!-- Scripts");
        str.append("================================================== -->");
        str.append("<script src='js/jquery-3.4.1.min.js'></script>");
        str.append("<script src='js/jquery-migrate-3.1.0.min.js'></script>");
        str.append("<script src='js/mmenu.min.js'></script>");
        str.append("<script src='js/tippy.all.min.js'></script>");
        str.append("<script src='js/simplebar.min.js'></script>");
        str.append("<script src='js/bootstrap-slider.min.js'></script>");
        str.append("<script src='js/bootstrap-select.min.js'></script>");
        str.append("<script src='js/snackbar.js'></script>");
        str.append("<script src='js/clipboard.min.js'></script>");
        str.append("<script src='js/counterup.min.js'></script>");
        str.append("<script src='js/magnific-popup.min.js'></script>");
        str.append("<script src='js/slick.min.js'></script>");
        str.append("<script src='js/custom.js'></script>");
        str.append("");
        str.append("<!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->");
        str.append("<script>");
        str.append("// Snackbar for user status switcher");
        str.append("$('#snackbar-user-status label').click(function() {");
        str.append("	Snackbar.show({");
        str.append("		text: 'Your status has been changed!',");
        str.append("		pos: 'bottom-center',");
        str.append("		showAction: false,");
        str.append("		actionText: 'Dismiss',");
        str.append("		duration: 3000,");
        str.append("		textColor: '#fff',");
        str.append("		backgroundColor: '#383838'");
        str.append("	});");
        str.append("});");
        str.append("</script>");
        str.append("");
        str.append("<!-- Chart.js // documentation: http://www.chartjs.org/docs/latest/ -->");
        str.append("<script src='js/chart.min.js'></script>");
        str.append("<script>");
        str.append("	Chart.defaults.global.defaultFontFamily = 'Nunito';");
        str.append("	Chart.defaults.global.defaultFontColor = '#888';");
        str.append("	Chart.defaults.global.defaultFontSize = '14';");
        str.append("");
        str.append("	var ctx = document.getElementById('chart').getContext('2d');");
        str.append("");
        str.append("	var chart = new Chart(ctx, {");
        str.append("		type: 'line',");
        str.append("");
        str.append("		// The data for our dataset");
        str.append("		data: {");
        str.append("			labels: ['January', 'February', 'March', 'April', 'May', 'June'],");
        str.append("			// Information about the dataset");
        str.append("	   		datasets: [{");
        str.append("				label: 'Views',");
        str.append("				backgroundColor: 'rgba(42,65,232,0.08)',");
        str.append("				borderColor: '#2a41e8',");
        str.append("				borderWidth: '3',");
        str.append("				data: [5,21,32,16,0,0],");
        str.append("				pointRadius: 5,");
        str.append("				pointHoverRadius:5,");
        str.append("				pointHitRadius: 10,");
        str.append("				pointBackgroundColor: '#fff',");
        str.append("				pointHoverBackgroundColor: '#fff',");
        str.append("				pointBorderWidth: '2',");
        str.append("			}]");
        str.append("		},");
        str.append("");
        str.append("		// Configuration options");
        str.append("		options: {");
        str.append("");
        str.append("		    layout: {");
        str.append("		      padding: 10,");
        str.append("		  	},");
        str.append("");
        str.append("			legend: { display: false },");
        str.append("			title:  { display: false },");
        str.append("");
        str.append("			scales: {");
        str.append("				yAxes: [{");
        str.append("					scaleLabel: {");
        str.append("						display: false");
        str.append("					},");
        str.append("					gridLines: {");
        str.append("						 borderDash: [6, 10],");
        str.append("						 color: '#d8d8d8',");
        str.append("						 lineWidth: 1,");
        str.append("	            	},");
        str.append("				}],");
        str.append("				xAxes: [{");
        str.append("					scaleLabel: { display: false },");
        str.append("					gridLines:  { display: false },");
        str.append("				}],");
        str.append("			},");
        str.append("");
        str.append("		    tooltips: {");
        str.append("		      backgroundColor: '#333',");
        str.append("		      titleFontSize: 13,");
        str.append("		      titleFontColor: '#fff',");
        str.append("		      bodyFontColor: '#fff',");
        str.append("		      bodyFontSize: 13,");
        str.append("		      displayColors: false,");
        str.append("		      xPadding: 10,");
        str.append("		      yPadding: 10,");
        str.append("		      intersect: false");
        str.append("		    }");
        str.append("		},");
        str.append("");
        str.append("");
        str.append("});");
        str.append("");
        str.append("</script>");
        str.append("");
        str.append("</body>");
        str.append("</html>");
               
        return str.toString();
    }
}